linters-settings:
  nlreturn:
    block-size: 3
  staticcheck:
    checks: ["all"]
  stylecheck:
    checks: ["all"]
  funlen:
    lines: 200
  cyclop:
    max-complexity: 30
  varnamelen:
    max-distance: 15
    ignore-names:
      - err # error values
      - w # io.Writers
      - r # io.Readers or http.Request
      - ok # common bool
linters:
  enable-all: true
  disable:
    - dupl # false positive galore
    - exhaustruct # CDK has large structs we use partially
    - gochecknoinits # frameworks and magefile use init responsibly
    - gci # no way to automate this in the vscode so default ordering is good enough
    - ireturn # our oapi implementations return interfaces all the time
    - tagliatelle # we have lots of aws tags that don't follow the standards
    - nonamedreturns # makes some functions very unreadable
    - wsl # too strict
    - gochecknoglobals # too strict
    - gomoddirectives # can't get this to shutup
    - goconst # text identifiers makes it more readable
    - funlen # trust our own judgement
    - err113 # too much effort
    - perfsprint #microoptimization
    - canonicalheader
    - unparam # don't be too smart
    - dupword # gets in the way often when we're commenting out stuff
    - containedctx # actually common for actors/workers that have a context for the lifetime
    - paralleltest # too anoying
    - nlreturn # too annoying for small functions
    - mnd # just too annoying
    - wrapcheck
    - exportloopref # deprecated
    - thelper # not usefull it seems
    - depguard

issues:
  include:
    - EXC0015 # warn for lack of package comment
    - EXC0013 # warn for lack of package comment
    - EXC0014 # EXC0014 revive: Annoying issue about not having a comment. The rare codebase has such comments
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - dupl
        - gosec
        - forcetypeassert
        - gochecknoglobals
        - lll
        - err113
        - revive
        - perfsprint
        - wrapcheck
        - nlreturn
        - varnamelen
        - errcheck
        - nilnil
